#!/bin/sh

case $1 in
        start)
                ifconfig eth0 192.168.1.5 netmask 255.255.255.0
                route add default gw 192.168.1.1
                echo "nameserver 8.8.8.8" > /etc/resolv.conf
               
                ;;
        stop)
                ;;
        *)
                exit 1
                ;;
esac
